import { DayConfig } from './types';

export const DEFAULT_DAYS: DayConfig[] = [
  {
    id: 'segunda',
    name: 'Segunda-feira',
    shortName: 'Seg',
    emoji: '🌊',
    subtitle: 'Vamos começar bem a semana, Marcus! 💪',
    color: '#3B82F6',
    lightColor: '#EFF6FF',
    darkColor: '#1E40AF',
    mission: { icon: '⭐', text: 'Guardar toda a louça limpa da lava-louças' },
    tasks: [
      { id: 's1', time: '12:00', name: 'Chegar da escola', emoji: '🏫' },
      { id: 's2', time: '12:15', name: 'Almoço', emoji: '🍽️' },
      { id: 's3', time: '12:45', name: 'Descanso', emoji: '😴', note: '30 minutos' },
      { id: 's4', time: '13:15', name: 'Lição de casa', emoji: '📚' },
      {
        id: 's5', time: '14:00', name: 'Guardar a louça da lava-louças',
        emoji: '🫙', note: '15 minutos', isMission: true,
      },
      { id: 's6', time: '14:20', name: 'Jogos', emoji: '🎮' },
      { id: 's7', time: '15:30', name: 'Lanche', emoji: '🥪' },
      { id: 's8', time: '16:00', name: 'Curso de Desenho', emoji: '📚' },
      { id: 's9', time: '18:00', name: 'Banho', emoji: '🚿' },
      { id: 's10', time: '19:00', name: 'Jantar', emoji: '🍝' },
      { id: 's11', time: '20:00', name: 'Jogos em família, leitura ou desenho', emoji: '👨‍👩‍👦' },
      { id: 's12', time: '21:00', name: 'Dormir', emoji: '🌙' },
    ],
  },
  {
    id: 'terca',
    name: 'Terça-feira',
    shortName: 'Ter',
    emoji: '🌿',
    subtitle: 'Dia de cuidar dos bichinhos! 🐾',
    color: '#10B981',
    lightColor: '#ECFDF5',
    darkColor: '#065F46',
    mission: { icon: '🐾', text: 'Trocar a água do gato e dos cachorros' },
    tasks: [
      { id: 't1', time: '12:00', name: 'Chegar da escola', emoji: '🏫' },
      { id: 't2', time: '12:15', name: 'Almoço', emoji: '🍽️' },
      { id: 't3', time: '13:00', name: 'Descanso', emoji: '😴' },
      { id: 't4', time: '13:30', name: 'Lição de casa', emoji: '📚' },
      {
        id: 't5', time: '14:15', name: 'Cuidar dos pets', emoji: '🐾',
        isMission: true,
        subTasks: [
          { id: 't5a', name: 'Trocar água do gato', emoji: '💧' },
          { id: 't5b', name: 'Trocar água dos cachorros', emoji: '💧' },
          { id: 't5c', name: 'Verificar ração', emoji: '🥣' },
          { id: 't5d', name: 'Brincar 10 minutos', emoji: '🎾' },
        ],
      },
      { id: 't6', time: '15:00', name: 'Jogos', emoji: '🎮' },
      { id: 't7', time: '16:00', name: 'Desenho livre', emoji: '🎨' },
      { id: 't8', time: '17:30', name: 'Passeio com o cachorro', emoji: '🐕', note: 'Com um adulto, se possível 🙂' },
      { id: 't9', time: '19:00', name: 'Jantar', emoji: '🍝' },
      { id: 't10', time: '20:00', name: 'Tempo livre', emoji: '⭐' },
    ],
  },
  {
    id: 'quarta',
    name: 'Quarta-feira',
    shortName: 'Qua',
    emoji: '🎨',
    subtitle: 'Dia do curso de desenho! Arrasa! 🖌️',
    color: '#F59E0B',
    lightColor: '#FFFBEB',
    darkColor: '#92400E',
    mission: { icon: '🧸', text: 'Organizar os brinquedos por 15 minutos' },
    tasks: [
      { id: 'q1', name: 'Escola', emoji: '🏫' },
      { id: 'q2', name: 'Almoço', emoji: '🍽️' },
      { id: 'q3', name: 'Lição de casa', emoji: '📚' },
      { id: 'q4', name: 'Guardar brinquedos', emoji: '🧸', note: '15 minutos', isMission: true },
      { id: 'q5', name: 'Curso de desenho', emoji: '🖌️' },
      { id: 'q6', name: 'Tempo livre', emoji: '⭐' },
      { id: 'q7', name: 'Dormir', emoji: '🌙' },
    ],
  },
  {
    id: 'quinta',
    name: 'Quinta-feira',
    shortName: 'Qui',
    emoji: '🏊',
    subtitle: 'Natação hoje — você é um peixe! 🐟',
    color: '#8B5CF6',
    lightColor: '#F5F3FF',
    darkColor: '#4C1D95',
    mission: { icon: '🧺', text: 'Dobrar toalhas ou panos' },
    tasks: [
      { id: 'u1', name: 'Escola', emoji: '🏫' },
      { id: 'u2', name: 'Almoço', emoji: '🍽️' },
      { id: 'u3', name: 'Lição de casa', emoji: '📚' },
      { id: 'u4', name: 'Dobrar toalhas', emoji: '🧺', isMission: true, note: 'Organizado como um campeão!' },
      { id: 'u5', name: 'Natação', emoji: '🏊' },
      { id: 'u6', name: 'Banho', emoji: '🚿' },
      { id: 'u7', name: 'Jantar', emoji: '🍝' },
    ],
  },
  {
    id: 'sexta',
    name: 'Sexta-feira',
    shortName: 'Sex',
    emoji: '🎉',
    subtitle: 'Quase fim de semana — você conseguiu! 🙌',
    color: '#EC4899',
    lightColor: '#FDF2F8',
    darkColor: '#831843',
    mission: { icon: '🎒', text: 'Preparar a mochila para a segunda-feira' },
    tasks: [
      { id: 'x1', name: 'Escola', emoji: '🏫' },
      { id: 'x2', name: 'Almoço', emoji: '🍽️' },
      { id: 'x3', name: 'Lição de casa', emoji: '📚' },
      { id: 'x4', name: 'Organizar quarto', emoji: '🗂️', note: '15 minutos' },
      { id: 'x5', name: 'Jogos online', emoji: '🎮' },
      { id: 'x6', name: 'Preparar mochila para segunda', emoji: '🎒', isMission: true, note: 'Separar material, conferir agenda' },
      { id: 'x7', name: 'Filme com a família', emoji: '🎬', note: '🍿' },
    ],
  },
  {
    id: 'sabado',
    name: 'Sábado',
    shortName: 'Sáb',
    emoji: '🎊',
    subtitle: 'Fim de semana! Hora de aventura! 🚀',
    color: '#EF4444',
    lightColor: '#FEF2F2',
    darkColor: '#7F1D1D',
    mission: { icon: '🐕', text: 'Ajudar a alimentar os pets' },
    tasks: [
      { id: 'b1', name: 'Passeio', emoji: '🚶' },
      { id: 'b2', name: 'Parque', emoji: '🌳' },
      { id: 'b3', name: 'Bicicleta', emoji: '🚴' },
      { id: 'b4', name: 'Kung Fu', emoji: '🥋', note: 'Se for matriculado 😄' },
      { id: 'b5', name: 'Desenho', emoji: '🎨' },
      { id: 'b6', name: 'Jogos', emoji: '🎮' },
      { id: 'b7', name: 'Ajudar a alimentar os pets', emoji: '🐕', isMission: true },
      { id: 'b8', name: 'Tempo em família', emoji: '👨‍👩‍👦' },
      { id: 'b9', name: 'Pizza! 🎉', emoji: '🍕' },
      { id: 'b10', name: 'Filme', emoji: '🎬', note: '🍿' },
    ],
  },
  {
    id: 'domingo',
    name: 'Domingo',
    shortName: 'Dom',
    emoji: '🌈',
    subtitle: 'Descanso e preparação para a nova semana 🌟',
    color: '#06B6D4',
    lightColor: '#ECFEFF',
    darkColor: '#0E7490',
    mission: { icon: '📋', text: 'Revisar quarto e separar roupa da escola' },
    tasks: [
      { id: 'd1', name: 'Escolher roupa da segunda-feira', emoji: '👕', isMission: true },
      { id: 'd2', name: 'Organizar a mochila', emoji: '🎒', isMission: true },
      { id: 'd3', name: 'Separar material escolar', emoji: '📏', isMission: true },
      { id: 'd4', name: 'Brincar', emoji: '🎮' },
      { id: 'd5', name: 'Descansar', emoji: '😴' },
      { id: 'd6', name: 'Dormir cedo — amanhã é semana nova! 🚀', emoji: '🌙' },
    ],
  },
];

export const DAY_ORDER = ['segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado', 'domingo'];

export function getDayById(id: string, customDays?: DayConfig[]): DayConfig | undefined {
  const source = customDays ?? DEFAULT_DAYS;
  return source.find((d) => d.id === id);
}

/** Maps JS getDay() (0=Sun) to our day IDs */
export const JS_DAY_TO_ID: Record<number, string> = {
  0: 'domingo',
  1: 'segunda',
  2: 'terca',
  3: 'quarta',
  4: 'quinta',
  5: 'sexta',
  6: 'sabado',
};
